import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { withTenantTx } from '../../lib/db.js';
import { requirePermission, visibleUserIds, requireAssignableUser, requireOwnedRecord } from '../../lib/permissions.js';
import { addActivity, audit, outbox } from '../../lib/domain.js';
const createSchema=z.object({title:z.string().min(1),description:z.string().optional(),priority:z.enum(['LOW','MEDIUM','HIGH','URGENT']).default('MEDIUM'),assignedToUserId:z.string().uuid().optional(),dueAt:z.string().datetime().optional(),companyId:z.string().uuid().optional(),contactId:z.string().uuid().optional(),opportunityId:z.string().uuid().optional(),customFields:z.record(z.unknown()).default({})});
export async function taskRoutes(app:FastifyInstance){app.addHook('onRequest',app.authenticate);
  app.get('/',async request=>{requirePermission(request.auth,'task.read');return withTenantTx(request.auth,async client=>{const users=await visibleUserIds(client,request.auth);const params:unknown[]=[request.auth.workspaceId];let scope='';if(users){params.push(users);scope=` AND assigned_to_user_id=ANY($2::uuid[])`;}const r=await client.query(`SELECT * FROM tasks WHERE workspace_id=$1 AND deleted_at IS NULL${scope} ORDER BY completed_at NULLS FIRST,due_at NULLS LAST LIMIT 100`,params);return{data:r.rows};});});
  app.post('/',async(request,reply)=>{requirePermission(request.auth,'task.create');const b=createSchema.parse(request.body);return withTenantTx(request.auth,async client=>{const assignee=b.assignedToUserId??request.auth.userId;await requireAssignableUser(client,request.auth,assignee);const r=await client.query(`INSERT INTO tasks(workspace_id,title,description,priority,assigned_to_user_id,created_by_user_id,due_at,company_id,contact_id,opportunity_id,custom_fields) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb) RETURNING *`,[request.auth.workspaceId,b.title,b.description??null,b.priority,assignee,request.auth.userId,b.dueAt??null,b.companyId??null,b.contactId??null,b.opportunityId??null,JSON.stringify(b.customFields)]);const task=r.rows[0];await addActivity(client,request.auth,{type:'TASK_CREATED',title:`Tarefa criada: ${task.title}`,companyId:task.company_id,contactId:task.contact_id,opportunityId:task.opportunity_id,taskId:task.id});await audit(client,request.auth,{action:'task.created',entityType:'task',entityId:task.id,after:task,requestId:request.id});reply.code(201);return task;});});
  app.post('/:id/complete',async(request,reply)=>{requirePermission(request.auth,'task.update');const id=z.string().uuid().parse((request.params as any).id);return withTenantTx(request.auth,async client=>{await requireOwnedRecord(client,request.auth,'tasks',id);const before=(await client.query(`SELECT * FROM tasks WHERE workspace_id=$1 AND id=$2 AND deleted_at IS NULL FOR UPDATE`,[request.auth.workspaceId,id])).rows[0];if(before.status==='COMPLETED')return before;const r=await client.query(`UPDATE tasks SET status='COMPLETED',completed_at=now() WHERE workspace_id=$1 AND id=$2 RETURNING *`,[request.auth.workspaceId,id]);const task=r.rows[0];await addActivity(client,request.auth,{type:'TASK_COMPLETED',title:`Tarefa concluída: ${task.title}`,companyId:task.company_id,contactId:task.contact_id,opportunityId:task.opportunity_id,taskId:id});await audit(client,request.auth,{action:'task.completed',entityType:'task',entityId:id,before,after:task,requestId:request.id});await outbox(client,request.auth,{aggregateType:'task',aggregateId:id,eventType:'TaskCompleted',payload:{taskId:id,opportunityId:task.opportunity_id,assignedToUserId:task.assigned_to_user_id}});return task;});});
}
